
title: Open Systems Pharmacology
description: > # this means to ignore newlines until "baseurl:"
  Robust and reliable, easy-to-use modeling &amp; simulation tools, 
  processes and models for pharmaceutical and other life-sciences 
  applications qualified and accepted by a scientific community from academia,
  regulatory agencies and industry available and open to everyone.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.open-systems-pharmacology.org # the base hostname & protocol for your site, e.g. http://example.com
base: open-systems-pharmacology.org # the base hostname & protocol for your site, e.g. http://example.com
github: https://github.com/Open-Systems-Pharmacology/ 
github_suite_master: https://github.com/Open-Systems-Pharmacology/Suite/blob/master/
twitter_username: open-systems-pharmacology
github_username:  open-systems-pharmacology
tracking_id: UA-104123195-1

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

collections:
  news:
    output: false
    permalink: /:collection/:name
  examples:
    output: false  
    permalink: /:collection/:name
  tutorials:
    output: false  
    permalink: /:collection/:name
  
